<?php
/* @var $block \Mygento\Cloudpayments\Block\Capture */
?>
<script type="text/x-magento-init">
{"*":
    {"cloudPaymentsFrame": {
        "steps": "charge",
        "params": <?php echo $block->getWidgetData(); ?>,
        "baseUrl": "<?php echo $block->getBaseUrl(); ?>",
        "successPageUrl": "<?php echo $block->getSuccessPage(); ?>",
        "errorPageUrl": "<?php echo $block->getErrorPage(); ?>"
        }
    }
}
</script>
